basler_params:
  -
    name: AcquisitionFrameRateAbs
    type: float
    value: 100.0
  -
    name: ExposureTimeAbs
    type: float
    value: 20000.0
  -
    name: AcquisitionMode
    type: enum
    value: Continuous
  -
    name: BalanceWhiteAuto
    type: enum
    value: 'Once'
  -
    name: TriggerMode
    type: enum
    value: 'On'
  -
    name: TriggerSource
    type: enum
    value: Line1
  -
    name: LineSelector
    type: enum
    value: Line1
  -
    name: LineMode
    type: enum
    value: Input
  -
    name: TriggerSelector
    type: enum
    value: FrameStart 
  -
    name: TriggerActivation
    type: enum
    value: RisingEdge
  -
    name: GevSCPSPacketSize
    type: int
    value: 9000
  -
    name: GevSCPD
    type: int
    value: 9021
  -
    name: GevSCFTD
    type: int
    value: 0
